# Generated by Django 4.2.5 on 2024-01-10 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorDetails',
            fields=[
                ('author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('affiliation', models.CharField(max_length=45)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('publication_year', models.IntegerField()),
                ('authorname', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publication_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('publication_year', models.IntegerField()),
                ('authors', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.authordetails')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.project')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField()),
                ('journal', models.CharField(max_length=150)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.publication')),
            ],
        ),
    ]
