# Generated by Django 4.2.5 on 2024-02-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authordetails',
            name='attended_date',
            field=models.IntegerField(null=True),
        ),
    ]
